name: Ruby-github-actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0 # ご使用のRubyのバージョン確認
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run tests
        run: rake test # テストタスクの設定が必要 Minitest
